### PR TITLE
Use namespaced constants

### PR DESCRIPTION
**Pull request by szepeviktor**
These are only definitions.

### CODE REVIEW

**Comment by szepeviktor** [comment]
```diff
- $output->writeln(\WPTS_CMD_INTRO);
+ $output->writeln(\WPTS\CMD_INTRO);
```

**Review by SebKay — CHANGES_REQUESTED** [review]
Looks like the uses of these definitions weren't updated.

Please see failed workflow for more info.

**Comment by szepeviktor** [comment]
> Looks like the uses of these definitions weren't updated.

Yes, I know. This was not meant to be a complete PR.

Now done 🟢

**Review by SebKay — APPROVED** [review]

**Comment by SebKay** [comment]
@szepeviktor Thanks for the contribution. Very much appreciated!

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
